# .github/workflows/tag-and-run.yml
name: Tag and Run Script

on:
  push:
    branches:
      - dev
env:
  tag: v-1.0.0

jobs:
  tag_and_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Clone repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 3: Create a new tag
      - name: Create a tag
        id: create_tag
        run: |
          TAG_NAME="$tag"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Code To ETE
        env:
          REPO_URL: "https://github.com/shivakumar-darapu/DevOpsPipeline-ETE.git"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git remote add target_repo https://x-access-token:${REPO_TOKEN}@${REPO_URL}
          git remote add target_repo $REPO_URL
          git push target_repo ${{ env.tag }}  # Push the tag
          git push target_repo dev:dev
