# .github/workflows/tag-and-run.yml
name: Tag and Run Script

on:
  push:
    branches:
      - dev
env:
  tag: v-1.0.3

jobs:
  tag_and_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Clone repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --local user.name "shivakumar-darapu"
          git config --local user.email "darapushivakumar@gmail.com"

      # Step 3: Create a new tag
      - name: Create a tag
        id: create_tag
        run: |
          TAG_NAME="$tag-$date"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Code To ETE
        env:
          REPO_URL: "shivakumar-darapu/DevOpsPipeline-ETE"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          FULL_REPO_URL="https://x-access-token:${REPO_TOKEN}@github.com/${REPO_URL}.git"
          if git remote get-url target_repo; then
            git remote set-url target_repo $FULL_REPO_URL
          else
            git remote add target_repo $FULL_REPO_URL
          fi
      
      - name: Debug Remote
        run: git remote -v  # To verify the remote is set correctly

      - name: Push to another repository
        run: |
          git push target_repo dev:dev  # Change branches as needed